### ISSUE TITLE
Associate a page with a title in sections 

### ISSUE THREAD

**Issue by malkij** [StefMa/hugo-fresh#112]
Hello,
Is it possible to associate  an md page like "content/docs/example.md" to a url of a title in sections  : 
```yaml
section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: <====== put the content here 
      buttonText: Free trial
```
Thank you.
