### ISSUE TITLE
Support multilingual mode

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#120]
Currently the setup of the site together with text are done in the configuration file.
See for example
https://github.com/StefMa/hugo-fresh/blob/6b7327731336dd250a5deb54f56b0a364ae68ced/exampleSite/config.yaml#L29-L31
This prevents users to create sites in different languages.

This theme should support the multilingual mode described [this hugo documentation](https://gohugo.io/content-management/multilingual/).

See also https://discourse.gohugo.io/t/hugo-fresh-config-yaml-params-internationalization/31127

**Comment by StefMa** [comment]
What was mentioned above *is not true*.
I just read the documentation and the theme supports different langauge already quite well.

I testet a little bit and came up with the following configuration:
```yaml
defaultContentLanguage: en

languages:
  de:
    title: Ein deutscher Titel
    navbar:
    - title: Features
      url: /
    - title: Preise
      url: /
    - title: Fallen
      sublinks:
      - title: Fallen item
        url: /
      - title: Fallen item
        url: /
      - title: Fallen item
        url: /
    - title: Anmelden
      url: /
    - title: Registrieren
      url: /
      button: true
  en:
    title: Another Title, just for testing
```
This give us support for english as well as german.
As you can see, it is possible to override the *params* in the languages.
Therefore it is a simple "override" in the configuration to support different languages.

The english `defaultContentLanguage` version can be found under the `baseUrl`.
The german version can be found under `baseUrl/de`

If you want to support different single-pages you only have to add the language-identifier to the markdown file.
E.g. `agb.md` (default/fallback), `agb.de.md` (german)

I'll close this because it is supported and I don't see a reason why we should change something.
