### ISSUE TITLE
Sidebar example and documentation 

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#121]
The sidebar option is not documented nor showed as an example.

Add the option to the readme and to the example site.

**Comment by StefMa** [comment]
This is how an sidebar can be configured:
```yaml
  sidebar:
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: More
      icon: another-icon
      links:
      - text: Special More
        url: /
      - text: Even More
        url: /
```
