### ISSUE TITLE
sidebar clashes with single-page without sidebar

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#122]
Given a config file with a sidebar:
```yaml
  sidebar:
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
```

and a single page without sidebar:
```markdown
---
title: AGB
include_footer: true
---
```

The single page will render the sidebar icon but will not show anything.
![Geist_1613029251918](https://user-images.githubusercontent.com/10229883/107611715-e924a180-6c44-11eb-8939-214dd4dee796.gif)

Expected behaviour:
There is no sidebar icon.
