### ISSUE TITLE
Include quicklinks in footer

### ISSUE THREAD

**Issue by clsource** [StefMa/hugo-fresh#37]
The current theme does not render the quicklinks in the footer because the `config.yaml` does not have proper configuration in the `footer`.

This should work I think.

```yaml
quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: Request features
          link: /
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /
        - text: Tech articles
          link: /
        - text: Video blog
          link: /
```
