### ISSUE TITLE
Include navbarlogo in config

### ISSUE THREAD

**Issue by adamwooding** [StefMa/hugo-fresh#45]
Hi, thank you so much for this fantastic Hugo theme 👍 

Just a small issue - the current theme does not seem to render the navbar logo in the navbar because the `config.yaml` does not include any configuration for the `navbarlogo`.

This seems to work (for me):

```
params:
 navbarlogo:
  image: logos/logo.svg
  link: /
```

Thanks again!
