### ISSUE TITLE
Text in partial footer "Follow us" is hard coded

### ISSUE THREAD

**Issue by rolfkbk** [StefMa/hugo-fresh#48]
Should be a variable so template can be used in other languages

**Comment by StefMa** [comment]
The text is hardcoded here:
https://github.com/StefMa/hugo-fresh/blob/3b52fc46e469babfa48732605d635ba4611bde2e/layouts/partials/footer.html#L35

You are absolutely right.
That should be done in the `config.yml`

I would suggest we do something like:
```yml
footer:
  socialmedia:
   title: "Follow us"
   links: 
    link: github.com
    icon: github
```
