### ISSUE TITLE
Sidebar with single pages are broken

### ISSUE THREAD

**Issue by StefMa** [StefMa/hugo-fresh#64]
We can enable the sidebar by adding this to our `config.yml` file:
```
  sidebar:
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
        - text: Profile
          url: /
```
This works as expected and enable the sidebar to our main page **and** on single pages with its own sidebar:
![Geist_1563952924999](https://user-images.githubusercontent.com/10229883/61773332-bada3980-adf4-11e9-8be0-dc854ecc9a2e.gif)
![Geist_1563952974090](https://user-images.githubusercontent.com/10229883/61773335-bb72d000-adf4-11e9-81c7-d6d44e69e588.gif)

But it doesn't work on single pages without a sidebar.
The sidebar is visible **but can't be shown**:
![Geist_1563952950651](https://user-images.githubusercontent.com/10229883/61773362-cb8aaf80-adf4-11e9-9608-a36645242589.gif)

We should disable the sidebar (link)/(opener) on single pages without a sidebar completely!
