### ISSUE TITLE
Font awesome gitlab icon not displayed in footer

### ISSUE THREAD

**Issue by thomasboni** [StefMa/hugo-fresh#71]
Gitlab icon is avaible on font awesome (https://fontawesome.com/v4.7.0/icon/gitlab/).

But when I try to use it in this theme it doesn't work:
```
footer:
     # Logo (from /images/logos/___)
     logo: fresh-white-alt.svg
     socialmedia:
       # Icons are from Font Awesome
     - link:  "#"
       icon: github
     - link: "#"
       icon: gitlab
     - link:  "#"
       icon: twitter
```

Github and Twitter works fine but gitlab doesn't works (display nothing). Maybe I miss some step ?
