### ISSUE TITLE
section2 images are not being displayed on Firefox Browsers

### ISSUE THREAD

**Issue by nathanbiller** [StefMa/hugo-fresh#98]
Both Chrome and Safari correctly show these SVG icons, but when Firefox renders they're missing.

![Screenshot 2019-11-17 14 48 25](https://user-images.githubusercontent.com/13682301/69013034-a1cc3a00-0949-11ea-95ba-4859bf38bf90.png)

**Comment by edwardch** [comment]
@nathanbiller this seems to be the svg file (really large) that needs to have its size specified. 
For reference I used a 150px .png file and it displayed fine.

I fixed this by editing the `//Icon box` in `_sections.scss`

```scss
//Icon box
.media.icon-box {
    border-top: none !important;
    .media-content .content p {
        span {
            display: block;
        }
        .icon-box-title {
            color: $blue-grey;
            font-size: 1.2rem;
            font-weight: 600;
        }
        .icon-box-text {
            color: $title-grey;
            font-size: 1rem;
            font-weight: 400;
        }
    }
    // Add this here
    img {
        height: 150px;
        width: 150px;
    }
}
```

hth
